// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createCategorie = `-- name: CreateCategorie :exec
insert into categories (id, name, description) values (?,?,?)
`

type CreateCategorieParams struct {
	ID          string
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateCategorie(ctx context.Context, arg CreateCategorieParams) error {
	_, err := q.db.ExecContext(ctx, createCategorie, arg.ID, arg.Name, arg.Description)
	return err
}

const createCourses = `-- name: CreateCourses :exec
insert into courses (id, category_id , name, description, price) values (?,?,?,?,?)
`

type CreateCoursesParams struct {
	ID          string
	CategoryID  string
	Name        string
	Description sql.NullString
	Price       float64
}

func (q *Queries) CreateCourses(ctx context.Context, arg CreateCoursesParams) error {
	_, err := q.db.ExecContext(ctx, createCourses,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
	)
	return err
}

const deleteCategorie = `-- name: DeleteCategorie :exec
delete from categories where id = ?
`

func (q *Queries) DeleteCategorie(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCategorie, id)
	return err
}

const listCategorie = `-- name: ListCategorie :one
select id, name, description from categories where id = ?
`

func (q *Queries) ListCategorie(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRowContext(ctx, listCategorie, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const listCategories = `-- name: ListCategories :many
select id, name, description from categories
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
select c.id, c.category_id, c.name, c.description, c.price, ca.name as category_name 
from courses c join categories ca on c.category_id = ca.id
`

type ListCoursesRow struct {
	ID           string
	CategoryID   string
	Name         string
	Description  sql.NullString
	Price        float64
	CategoryName string
}

func (q *Queries) ListCourses(ctx context.Context) ([]ListCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesRow
	for rows.Next() {
		var i ListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategorie = `-- name: UpdateCategorie :exec
update categories set name= ?, description=?  where id = ?
`

type UpdateCategorieParams struct {
	Name        string
	Description sql.NullString
	ID          string
}

func (q *Queries) UpdateCategorie(ctx context.Context, arg UpdateCategorieParams) error {
	_, err := q.db.ExecContext(ctx, updateCategorie, arg.Name, arg.Description, arg.ID)
	return err
}
